version: '3.8'

services:
  # Serviço 1: Banco de Dados MySQL
  aerocode-database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'aerocode'
      MYSQL_ROOT_PASSWORD: 'suasenha'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysql -u root -pSuasenha -e 'SELECT 1;' aerocode"]
      timeout: 5s
      retries: 10
      interval: 5s
      start_period: 15s 

  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app         
      - /app/node_modules
    environment:
      - DATABASE_URL=mysql://root:suasenha@aerocode-database:3306/aerocode
      - PORT=3000
    command: sh -c "npx prisma db push && npm run dev"
    depends_on:
      aerocode-database:
        condition: service_healthy

  prisma-studio:
      image: node:20-alpine
      container_name: aerocode-prisma-studio
      working_dir: /app
      volumes:
        - ./backend:/app
        - /app/node_modules 
      ports:
        - "5555:5555"
      environment:
        - DATABASE_URL=mysql://root:suasenha@aerocode-database:3306/aerocode
      command: sh -c "npm install && npx prisma generate && npx prisma studio --port 5555"
      depends_on:
        aerocode-database:
          condition: service_healthy

  # Serviço 3: Frontend React + Vite
  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app        
      - /app/node_modules       
    depends_on:
      - backend
    

volumes:
  mysql_data: