version: '3.8'

services:
  # Serviço 1: Banco de Dados MySQL
  aerocode-database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'aerocode'
      MYSQL_ROOT_PASSWORD: 'suasenha'
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app         
      - /app/node_modules
    environment:
      - DATABASE_URL=mysql://root:suasenha@aerocode-database:3306/aerocode
      - PORT=3000
    depends_on:
      - aerocode-database

  prisma-studio:
    image: node:20-alpine
    container_name: aerocode-prisma-studio
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5555:5555"
    command: npx prisma studio --port 5555
    depends_on:
      - aerocode-database

  # Serviço 3: Frontend React + Vite
  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app        
      - /app/node_modules       
    depends_on:
      - backend
    

volumes:
  mysql_data: